# intro deep learning with pytorch

In [3]:
import torch

In [4]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [5]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [12]:
torch.mm(features,weights.T)
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [18]:
activation(torch.sum(torch.mm(features,weights.T)+bias))

tensor(0.1595)

In [19]:
y= activation(torch.sum(features*weights)+bias)

In [20]:
y

tensor([[0.1595]])

In [47]:
torch.manual_seed(7)
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

w1 = torch.randn(n_input,n_hidden)
w2 = torch.randn(n_hidden,n_output)

b1 = torch.randn((1,n_hidden))
b2 = torch.randn((1,n_output))

# o1 = activation(torch.sum(torch.mm(features,w1)+b1))
# y = activation(torch.sum(torch.mm(o1,w2))+b2)
# y
o1 =activation(torch.mm(features,w1)+b1)
o1
o2 = activation(torch.mm(o1,w2)+b2)
o2


tensor([[0.3171]])