# intro deep learning with pytorch

In [3]:
import torch

In [4]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [5]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [12]:
torch.mm(features,weights.T)
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [18]:
activation(torch.sum(torch.mm(features,weights.T)+bias))

tensor(0.1595)

In [19]:
y= activation(torch.sum(features*weights)+bias)

In [20]:
y

tensor([[0.1595]])

In [47]:
torch.manual_seed(7)
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

w1 = torch.randn(n_input,n_hidden)
w2 = torch.randn(n_hidden,n_output)

b1 = torch.randn((1,n_hidden))
b2 = torch.randn((1,n_output))

# o1 = activation(torch.sum(torch.mm(features,w1)+b1))
# y = activation(torch.sum(torch.mm(o1,w2))+b2)
# y
o1 =activation(torch.mm(features,w1)+b1)
o1
o2 = activation(torch.mm(o1,w2)+b2)
o2


tensor([[0.3171]])

# numpy from pytorch

In [48]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.77454748, 0.68639831, 0.49689299],
       [0.44425626, 0.98170937, 0.81794555],
       [0.68798895, 0.83120132, 0.64200894],
       [0.18405373, 0.05334317, 0.37741735]])

In [49]:
b = torch.from_numpy(a)
b

tensor([[0.7745, 0.6864, 0.4969],
        [0.4443, 0.9817, 0.8179],
        [0.6880, 0.8312, 0.6420],
        [0.1841, 0.0533, 0.3774]], dtype=torch.float64)

In [50]:
b.numpy()

array([[0.77454748, 0.68639831, 0.49689299],
       [0.44425626, 0.98170937, 0.81794555],
       [0.68798895, 0.83120132, 0.64200894],
       [0.18405373, 0.05334317, 0.37741735]])

In [51]:
b.mul_(2)

tensor([[1.5491, 1.3728, 0.9938],
        [0.8885, 1.9634, 1.6359],
        [1.3760, 1.6624, 1.2840],
        [0.3681, 0.1067, 0.7548]], dtype=torch.float64)

In [52]:
a

array([[1.54909495, 1.37279663, 0.99378598],
       [0.88851251, 1.96341874, 1.6358911 ],
       [1.37597789, 1.66240265, 1.28401789],
       [0.36810747, 0.10668634, 0.7548347 ]])